export const data = {
  english: [
    {
      name: "Bachelor's Degree",
      image: 'graduation.svg',
      company: 'Universidade Metodista de São Paulo',
      duration: 'December 2020 (4 years)',
      color: 'orange',
      dark: false,
      description:
        'Graduated by the Methodist University of São Paulo in Rudge Ramos – São Bernardo do Campo, with 4 years of duration.',
    },
    {
      name: 'Digital Marketing',
      image: 'marketing.svg',
      duration: 'December 2018 (5 hours)',
      company: 'Getulio Vargas Foundation',
      color: 'blue',
      dark: false,
      description:
        'Self-institutional online course from the Getúlio Vargas Foundation that explains and teaches the foundations and techniques of the Digital Marketing and it’s applications.',
      certificate: 'marketing-digital.pdf',
    },
    {
      name: 'Information Technology and Communication',
      image: 'tic.svg',
      duration: 'December 2018 (14 hours)',
      company: 'SENAI',
      color: 'red',
      dark: false,
      description:
        'Introductory course about information technology and communication, that aims for the knowledge about hardware, network security notions, among other modules about the basic notions of ITC.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Search Engine Optimization',
      image: 'seo.svg',
      company: 'Udemy by Ricardo Zacho',
      duration: 'December 2018 (5 hours)',
      color: 'green',
      dark: false,
      description:
        'Online Course about the advanced notions of Search Engine Optimization, which is the optimization of content and development for a well-indexed website on the search engines (Google, Yahoo, Bing etc.)',
      certificate: 'seo.pdf',
    },
    {
      name: 'Interface Design',
      image: 'interface.svg',
      company: 'Udemy by Jamilton Damasceno +2',
      duration: 'December 2018 (15 hours)',
      color: 'yellow',
      dark: true,
      description:
        'Online Course to improve on theory and practice the concepts of UX and UI Design, Information Architecture, Prototyping as well as concepts of Usability, Wireframes and Layouts, Organizations and navigation Systems and much more.',
      certificate: 'ux-ui.pdf',
    },
    {
      name: 'Bootstrap 4',
      image: 'bootstrap.svg',
      company: 'Udemy by Ponto Courses',
      duration: 'December 2018 (10,5 hours)',
      color: 'purple',
      dark: false,
      description:
        'Complete Course of one of the biggest open source CSS frameworks. Learning about all the functionalities and options that the Bootstrap gives to the developer and to the consumer.',
      certificate: 'bootstrap.pdf',
    },
    {
      name: 'Tourism Monitoring',
      image: 'forma.svg',
      company: 'Forma Turismo',
      duration: 'February 2017 (40 hours)',
      color: 'yellow',
      dark: false,
      description:
        'A 40 hours course focused on the communicational accomplishment of Tourism. With neurolinguistics programming (NLP), Verbal and Non-Verbal communication, among other techniques that work with communication for the public.',
      certificate: 'tic.pdf',
    },
    {
      name: 'After Effects',
      image: 'after-effects-cc.svg',
      company: 'Puflix',
      duration: 'November 2017 (11 hours)',
      color: 'purple',
      dark: false,
      description:
        'Practical and theoretical course of After Effects CC done online in 2017 to improve the knowledge on animation and professional video editing.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Computer Graphics',
      image: 'computer-graphic.svg',
      company: 'SAGA',
      duration: 'October 2013 (3 years)',
      color: 'grey',
      dark: false,
      description:
        'Professional course of Computer Graphics done in Tatuapé (East Side of São Paulo), with a duration of 3 years. Modules on many softwares, such as After effects, Adobe Premiere, Dreamweaver, Fireworks, Photoshop, Autodesk Maya, and Digital Painting Techniques.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Introduction to Web Design',
      image: 'webdesign.svg',
      company: 'Objetiva School',
      duration: 'March 2010',
      color: 'blue',
      dark: false,
      description:
        'Introductory course of Web Design in software such as Macromedia Flash 8, Macromedia Fireworks 8, Macromedia Dreamweaver 8, that would eventually become Basic Adobe HTML, Basic CSS.',
      certificate: 'tic.pdf',
    },
  ],
  portuguese: [
    {
      name: 'Bacharelado em Publicidade e Propaganda',
      image: 'graduation.svg',
      company: 'Universidade Metodista de São Paulo',
      duration: 'Dezembro de 2020 (4 anos)',
      color: 'orange',
      dark: false,
      description:
        'Graduação presencial na Universidade Metodista de São Paulo, no Rudge Ramos - São Bernardo do Campo, com 4 anos de duração.',
    },
    {
      name: 'Marketing Digital',
      image: 'marketing.svg',
      duration: 'Dezembro de 2018 (5 horas)',
      company: 'Fundação Getulio Vargas',
      color: 'blue',
      dark: false,
      description:
        'Curso autoinstrucional a distância da Fundação Getúlio Vargas, que explica e instrui as técnicas e fundamentos do Marketing Digital e suas aplicações.',
      certificate: 'marketing-digital.pdf',
    },
    {
      name: 'Tecnologia da Informação e Comunicação',
      image: 'tic.svg',
      duration: 'Dezembro de 2018 (14 horas)',
      company: 'SENAI',
      color: 'red',
      dark: false,
      description:
        'Curso introdutório sobre Tecnologia da Informação e Comunicação, que visa os conhecimentos sobre hardware, noções de segurança de rede, entre outros módulos para noção básica de TIC.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Search Engine Optimization',
      image: 'seo.svg',
      company: 'Udemy por Ricardo Zacho',
      duration: 'Dezembro de 2018 (5 horas)',
      color: 'green',
      dark: false,
      description:
        'Curso on-line sobre as noções avançadas de Otimização de Mecanismos de Busca, que é a otimização de conteúdo e desenvolvimento para um site bem indexado nos mecanismos de busca (Google, Yahoo, Bing etc.)',
      certificate: 'seo.pdf',
    },
    {
      name: 'Design de Interface',
      image: 'interface.svg',
      company: 'Udemy por Jamilton Damasceno +2',
      duration: 'Dezembro de 2018 (15 horas)',
      color: 'yellow',
      dark: true,
      description:
        'Curso on-line para melhorar na teoria e na prática, os conceitos de UX Design, UI Design, Arquitetura de Informação, Prototipagem, além de conceitos de Usabilidade, Wireframes e Layouts, Sistemas de Organização e Navegação e muito mais.',
      certificate: 'ux-ui.pdf',
    },
    {
      name: 'Bootstrap 4',
      image: 'bootstrap.svg',
      company: 'Udemy por Ponto Courses',
      duration: 'December 2018 (10,5 hours)',
      color: 'purple',
      dark: false,
      description:
        'Curso completo de um dos maiores frameworks open source web. Aprendendo todas as funcionalidades e opções que o Bootstrap dispõe ao desenvolvedor e ao consumidor.',
      certificate: 'bootstrap.pdf',
    },
    {
      name: 'Monitoria e Turismo',
      image: 'forma.svg',
      company: 'Forma Turismo',
      duration: 'Fevereiro de 2017 (40 horas)',
      color: 'yellow',
      dark: false,
      description:
        'Curso presencial com carga horária de 40 Horas focada na realização comunicacional de Turismo. Com Programação Neurolinguística (PNL), comunicação verbal e não verbal, entre outras técnicas que colaboram com a comunicação com o público.',
      certificate: 'tic.pdf',
    },
    {
      name: 'After Effects',
      image: 'after-effects-cc.svg',
      company: 'Puflix',
      duration: 'Novembro de 2017 (11 horas)',
      color: 'purple',
      dark: false,
      description:
        'Curso prático e teórico de Adobe After Effects CC, realizado em 2017 a distância, para aumentar os conhecimentos em animação e edições profissionais de vídeos.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Computação Gráfica',
      image: 'computer-graphic.svg',
      company: 'SAGA',
      duration: 'Outubro 2013 (3 anos)',
      color: 'grey',
      dark: false,
      description:
        'Curso profissionalizante de computação gráfica realizado no bairro Tatuapé, na zona leste de São Paulo, com 3 anos de duração. Com uma carga de módulos nos mais diversos softwares, tais como, After Effects, Adobe Premiere, Dreaweaver, Fireworks, Photoshop, Autodesk Maya, e técnicas como Pintura Digital.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Introdução à Web Design',
      image: 'webdesign.svg',
      company: 'Escola Objetiva',
      duration: 'March 2010',
      color: 'blue',
      dark: false,
      description:
        'Curso intrudotório de Web Design em softwares como Macromedia Flash 8, Macromedia Fireworks 8, Macromedia Dreamweaver 8 - estes que posteriormente se tornariam Adobe - HTML Básico, CSS Básico.',
      certificate: 'tic.pdf',
    },
  ],
  german: [
    {
      name: 'Bachelorabschluss',
      image: 'graduation.svg',
      company: 'Universidade Metodista de São Paulo',
      duration: 'Dezember 2020 (4 Jahre)',
      color: 'orange',
      dark: false,
      description:
        'Abschluss an der methodistischen Universität von São Paulo in Rudge Ramos - São Bernardo do Campo mit einer Dauer von 4 Jahren.',
    },
    {
      name: 'Digital Marketing',
      image: 'marketing.svg',
      duration: 'Dezember 2018 (5 Stunden)',
      company: 'Getulio Vargas Foundation',
      color: 'blue',
      dark: false,
      description:
        'Selbstinstitutioneller Online-Kurs der Getúlio Vargas Foundation, der die Grundlagen und Techniken des digitalen Marketings und seiner Anwendungen erklärt und lehrt.',
      certificate: 'marketing-digital.pdf',
    },
    {
      name: 'Informationstechnologie und Kommunikation',
      image: 'tic.svg',
      duration: 'Dezember 2018 (14 Stunden)',
      company: 'SENAI',
      color: 'red',
      dark: false,
      description:
        'Einführungskurs über Informationstechnologie und Kommunikation, der auf das Wissen über Hardware, Netzwerksicherheitsbegriffe und andere Module über die Grundbegriffe von ITC abzielt.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Suchmaschinenoptimierung (SEO)',
      image: 'seo.svg',
      company: 'Udemy von Ricardo Zacho',
      duration: 'Dezember 2018 (5 Stunden)',
      color: 'green',
      dark: false,
      description:
        'Online-Kurs über die fortgeschrittenen Begriffe der Suchmaschinenoptimierung, dh die Optimierung von Inhalten und Entwicklung für eine gut indizierte Website in Suchmaschinen (Google, Yahoo, Bing usw.)',
      certificate: 'seo.pdf',
    },
    {
      name: 'Schnittstellen-Design',
      image: 'interface.svg',
      company: 'Udemy von Jamilton Damasceno +2',
      duration: 'Dezember 2018 (15 Stunden)',
      color: 'yellow',
      dark: true,
      description:
        'Online-Kurs zur Verbesserung von Theorie und Praxis der Konzepte von UX- und UI-Design, Informationsarchitektur, Prototyping sowie Konzepte von Usability, Wireframes und Layouts, Organisationen und Navigationssystemen und vielem mehr.',
      certificate: 'ux-ui.pdf',
    },
    {
      name: 'Bootstrap 4',
      image: 'bootstrap.svg',
      company: 'Udemy von Ponto Kurse',
      duration: 'Dezember 2018 (10,5 Stunden)',
      color: 'purple',
      dark: false,
      description:
        'Schließen Sie den Kurs eines der größten Open Source CSS-Frameworks ab. Erfahren Sie mehr über alle Funktionen und Optionen, die der Bootstrap dem Entwickler und dem Verbraucher bietet.',
      certificate: 'bootstrap.pdf',
    },
    {
      name: 'Tourismusüberwachung',
      image: 'forma.svg',
      company: 'Forma Turismo',
      duration: 'Februar 2017 (40 Stunden)',
      color: 'yellow',
      dark: false,
      description:
        'Ein 40-stündiger Kurs konzentrierte sich auf die kommunikative Leistung des Tourismus. Mit neurolinguistischer Programmierung (NLP), verbaler und nonverbaler Kommunikation, unter anderem Techniken, die mit Kommunikation für die Öffentlichkeit arbeiten.',
      certificate: 'tic.pdf',
    },
    {
      name: 'After Effects',
      image: 'after-effects-cc.svg',
      company: 'Puflix',
      duration: 'November 2017 (11 Stunden)',
      color: 'purple',
      dark: false,
      description:
        'Praktischer und theoretischer Kurs von After Effects CC, der 2017 online durchgeführt wurde, um das Wissen über Animation und professionelle Videobearbeitung zu verbessern.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Computergrafik',
      image: 'computer-graphic.svg',
      company: 'SAGA',
      duration: 'Oktober 2013 (3 Jahre)',
      color: 'grey',
      dark: false,
      description:
        'Professioneller Kurs für Computergrafik in Tatuapé (Ostseite von São Paulo) mit einer Dauer von 3 Jahren. Module für viele Software wie After Effects, Adobe Premiere, Dreamweaver, Fireworks, Photoshop, Autodesk Maya und digitale Maltechniken.',
      certificate: 'tic.pdf',
    },
    {
      name: 'Einführung in das Webdesign',
      image: 'webdesign.svg',
      company: 'Objetiva Schule',
      duration: 'März 2010',
      color: 'blue',
      dark: false,
      description:
        'Einführungskurs in Webdesign in Software wie Macromedia Flash 8, Macromedia Fireworks 8 und Macromedia Dreamweaver 8, die schließlich zu Basic Adobe HTML und Basic CSS werden sollte.',
      certificate: 'tic.pdf',
    },
  ],
};
